#!/usr/bin/env python3
__author__ = 'Thomas Funk'
__date__ = "2026/03/03"
__version__ = "0.2.0"

import os
import sys
import argparse
import atexit
import glob
import configparser
import shutil
import subprocess
import shlex
import time
import mmap
import tempfile
import mimetypes
import io
import json
import locale
import signal
import select
import re
from cairosvg import svg2png
from PIL import Image, ImageDraw, ImageFont, ImageEnhance
from pywayland.client import Display

# Add path to generated protocols (autogenerated by pywayland scanner)
sys.path.append(os.path.join(os.path.dirname(__file__), 'protocols'))

# Import required Wayland classes
from protocols.wayland.wl_compositor import WlCompositor
from protocols.wayland.zwlr_layer_shell_v1 import ZwlrLayerShellV1
from protocols.wayland.wl_region import WlRegion
from protocols.wayland.wl_shm import WlShm
from protocols.wayland.wl_seat import WlSeat
from protocols.wayland.wl_output import WlOutput

# Default paths for configuration, positions, and logs
DEFAULT_CONFIG_PATH = os.path.expanduser("~/.config/ldicons/ldicons.conf")
DEFAULT_POSITIONS_PATH = os.path.expanduser("~/.config/ldicons/icon_positions.json")
DEFAULT_LOG_PATH = os.path.expanduser("~/.config/ldicons/ldicons.log")


class TeeStream:
    """
    Writes output simultaneously to the original stream and the log file.
    """

    def __init__(self, original_stream, file_handle):
        self.original_stream = original_stream
        self.file_handle = file_handle

    def write(self, data):
        self.original_stream.write(data)
        self.file_handle.write(data)

    def flush(self):
        self.original_stream.flush()
        self.file_handle.flush()

    def isatty(self):
        return getattr(self.original_stream, "isatty", lambda: False)()


def setup_log_tee(log_path):
    """
    Enables output tee to console and log file.
    
    Parameters
    ----------
    
    log_path : str
        Target path of the log file.
    
    Returns
    -------
    
    object | None:
        Opened file handle or None.
    """
    if not log_path:
        return None

    expanded = os.path.expanduser(os.path.expandvars(log_path))
    log_dir = os.path.dirname(expanded)
    if log_dir:
        os.makedirs(log_dir, exist_ok=True)

    handle = open(expanded, "a", encoding="utf-8", buffering=1)
    sys.stdout = TeeStream(sys.stdout, handle)
    sys.stderr = TeeStream(sys.stderr, handle)
    print(f"Logging active: {expanded}")
    return handle


def parse_cli_args():
    """
    Parses command line arguments for ldicons.
    
    Returns
    -------
    
    argparse.Namespace:
        Parsed arguments.
    """
    parser = argparse.ArgumentParser(prog="ldicons", description="ldicons - Desktop-Icons for Wayland")
    parser.add_argument(
        "-c",
        "--conf",
        default=DEFAULT_CONFIG_PATH,
        help=f"Path to configuration file (default: {DEFAULT_CONFIG_PATH})",
    )
    parser.add_argument(
        "-l",
        "--log",
        default=DEFAULT_LOG_PATH,
        help=f"Path to log file (default: {DEFAULT_LOG_PATH})",
    )
    parser.add_argument(
        "-p",
        "--pos",
        default=DEFAULT_POSITIONS_PATH,
        help=f"Path to positions file (default: {DEFAULT_POSITIONS_PATH})",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose debug output.",
    )
    parser.add_argument(
        "-v",
        "--version",
        action="version",
        version=f"ldicons {__version__}",
    )
    return parser.parse_args()

class LDIcons:
    """
    Main class. Manages Wayland connection, icon data, interactions, and rendering.
    """
    # List of instance variables with type annotations for better overview in
    # VS Code explorer and later use
    display: Display
    registry: object

    width: int
    height: int
    scale: int
    outputs: list[object]

    layer_shell: object | None
    compositor: WlCompositor | None
    shm: WlShm | None
    seat: WlSeat | None
    pointer: object | None
    surface: object | None
    layer_surface: object | None
    configured: bool

    mouse_x: float
    mouse_y: float
    hover_index: int
    tooltip_visible: bool
    last_motion_time: float

    icons: list[dict]
    icon_cache: dict
    active_icon_themes: list[str]
    ui_font_name: str
    ui_font_family: str
    ui_font_point_size: float
    ui_font_path: str | None
    fallback_font_path: str
    ui_font_cache: dict[str, object]
    ui_font_debug_logged: set[str]

    last_click_time: float
    last_click_index: int
    double_click_timeout: float

    config_path: str
    desktop_path: str
    positions_path: str
    positions_path_locked: bool
    icon_positions: dict[str, dict[str, int]]

    menu_visible: bool
    menu_icon_index: int
    menu_pos: tuple[float, float]
    menu_items: list[str]
    menu_width: int
    menu_item_height: int

    left_pressed: bool
    pressed_icon_index: int
    dragging_index: int
    drag_start_mouse: tuple[float, float]
    drag_start_icon: tuple[float, float]
    drag_threshold: float

    icon_size: int
    label_bg: tuple[int, int, int, int]
    hover_bg: tuple[int, int, int, int]
    selection_bg: tuple[int, int, int, int]
    text_hover: tuple[int, int, int, int]
    text_selected: tuple[int, int, int, int]
    text_normal: tuple[int, int, int, int]
    tooltip_bg: tuple[int, int, int, int]
    spacing_x: int
    spacing_y: int
    grid_direction: str
    grid_wrap_count: int
    start_offset_x: int
    start_offset_y: int
    snap_grid_x: int
    snap_grid_y: int
    snap_origin_x: int
    snap_origin_y: int
    snap_to_grid: bool
    snap_avoid_overlap: bool
    tooltip_delay: float

    last_config_mtime: float
    last_desktop_mtime: float

    # --- Initialization / Configuration ---
    def __init__(self, config_path=None, positions_path=None, verbose=False):
        """
        Initializes Wayland connection, state fields, and base configuration.
        
        Parameters
        ----------
        config_path : str | None
            Optional path to the configuration file.
        
        positions_path : str | None
            Optional path to the positions file (JSON).
        
        verbose : bool
            Enables additional debug output.
        
        Raises
        ------
        
        RuntimeError
            If required Wayland interfaces cannot be bound.
        """
        # Establish connection to the Wayland socket
        display_name = self.get_latest_wayland_socket()
        self.display = Display(display_name)
        self.display.connect()
        
        self.registry = self.display.get_registry()

        # Monitor defaults
        self.width = 1920  
        self.height = 1080 
        self.scale = 1  
        self.outputs = []  
        
        # Wayland Interfaces
        self.layer_shell = None
        self.compositor = None
        self.shm = None
        self.seat = None
        self.pointer = None
        self.surface = None
        self.layer_surface = None
        self.configured = False # desktop_surface is only ready after ACK from the server

        # Interaction state
        self.mouse_x = 0
        self.mouse_y = 0
        self.hover_index = -1       
        self.tooltip_visible = False 
        self.last_motion_time = 0    

        # Icons and caching
        self.icons = []              
        self.icon_cache = {}
        self.active_icon_themes = []
        self.ui_font_name = ""
        self.ui_font_family = ""
        self.ui_font_point_size = 10.0
        self.ui_font_path = None
        self.fallback_font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
        self.ui_font_cache = {}
        self.ui_font_debug_logged = set()
        
        # Click handling
        self.last_click_time = 0
        self.last_click_index = -1
        self.double_click_timeout = 0.3 
        debug_env = os.environ.get(
            "LDICONS_INPUT_DEBUG",
            os.environ.get("LDICONS_INPUT_DEBUG", os.environ.get("LDICONS_INPUT_DEBUG", "0")),
        )
        self.input_debug = (debug_env == "1") or bool(verbose)
        self.left_pressed = False
        self.pressed_icon_index = -1
        self.dragging_index = -1
        self.drag_start_mouse = (0.0, 0.0)
        self.drag_start_icon = (0.0, 0.0)
        self.drag_threshold = 6.0
        self.snap_to_grid = True
        self.snap_avoid_overlap = True
        self.snap_grid_x = 140
        self.snap_grid_y = 180
        self.grid_direction = "vertical"
        self.grid_wrap_count = 0
        self.snap_origin_x = 50
        self.snap_origin_y = 50

        # Paths
        self.config_path = os.path.expanduser(config_path) if config_path else DEFAULT_CONFIG_PATH
        self.desktop_path = self.get_user_desktop_path()
        self.positions_path = os.path.expanduser(positions_path) if positions_path else DEFAULT_POSITIONS_PATH
        self.positions_path_locked = bool(positions_path)
        self.icon_positions = {}
        
        # Context menu (placeholder, as implementation in Wayland is complex)
        self.menu_visible = False
        self.menu_icon_index = -1
        self.menu_pos = (0, 0)
        self.menu_items = ["Öffnen", "Mit PCManFM öffnen", "Eigenschaften", "Löschen"]
        self.menu_width = 160
        self.menu_item_height = 30
        
        # Initial config load
        self.load_config()
        self.load_icon_positions()
        self.active_icon_themes = self.get_active_icon_themes(force_refresh=True)

        # Set registry handler and bind globals
        self.registry.dispatcher['global'] = self._registry_global_handler
        # Retrieve registry data and monitor information
        self.display.roundtrip()

        # Check whether required interfaces were bound, otherwise raise an error
        if not self.layer_shell or not self.compositor or not self.shm:
            raise RuntimeError("Konnte notwendige Wayland-Schnittstellen nicht binden!")

        # Initialize timestamps for live reload
        self.last_config_mtime = os.path.getmtime(self.config_path) if os.path.exists(self.config_path) else 0
        self.last_desktop_mtime = os.path.getmtime(self.desktop_path) if os.path.exists(self.desktop_path) else 0

    def get_latest_wayland_socket(self):
        """
        Determines the most recently active Wayland socket in the runtime directory.
        
        Returns
        -------
        str:
            Name of the Wayland socket (e.g. "wayland-0").
        """
        runtime_dir = os.environ.get('XDG_RUNTIME_DIR', f'/run/user/{os.getuid()}')
        sockets = glob.glob(f"{runtime_dir}/wayland-*")
        return os.path.basename(max(sockets, key=os.path.getmtime)) if sockets else 'wayland-0'

    def get_user_desktop_path(self):
        """
        Determines the desktop folder via XDG user dirs with fallbacks.
        
        Returns
        -------
        str:
            Absolute path to the current user's desktop folder.
        """
        home_dir = os.path.expanduser("~")

        # 1) xdg-user-dir (if available)
        try:
            result = subprocess.run(
                ["xdg-user-dir", "DESKTOP"],
                capture_output=True,
                text=True,
                check=False,
            )
            candidate = result.stdout.strip()
            if result.returncode == 0 and candidate:
                candidate = os.path.expandvars(candidate)
                candidate = os.path.expanduser(candidate)
                if os.path.isdir(candidate):
                    return candidate
        except Exception:
            pass

        # 2) Parse ~/.config/user-dirs.dirs
        user_dirs_file = os.path.join(home_dir, ".config", "user-dirs.dirs")
        try:
            if os.path.exists(user_dirs_file):
                with open(user_dirs_file, "r", encoding="utf-8") as file_obj:
                    for raw_line in file_obj:
                        line = raw_line.strip()
                        if not line.startswith("XDG_DESKTOP_DIR="):
                            continue
                        value = line.split("=", 1)[1].strip().strip('"')
                        value = value.replace("$HOME", home_dir)
                        candidate = os.path.expandvars(value)
                        candidate = os.path.expanduser(candidate)
                        if os.path.isdir(candidate):
                            return candidate
                        return candidate
        except Exception:
            pass

        # 3) Common fallbacks
        # for fallback in ("Desktop", "Desktop_German"):
        #     candidate = os.path.join(home_dir, fallback)
        #     if os.path.isdir(candidate):
        #         return candidate

        return os.path.join(home_dir, "Desktop")

    def load_config(self):
        """
        Reads the configuration file or sets default values.
        """
        config = configparser.ConfigParser()
        if os.path.exists(self.config_path):
            config.read(self.config_path)
        
        def get_color(section, key, default):
            try:
                s = config.get(section, key)
                return tuple(map(int, s.split(',')))
            except:
                return default

        # Resolve theme colors to use as fallbacks for configuration values
        theme_select_bg, theme_select_fg = self.get_theme_selection_colors()
        self.ui_font_name = self.get_active_gtk_font_name() or ""
        self.ui_font_family, self.ui_font_point_size = self._split_gtk_font_name(self.ui_font_name)
        self.ui_font_path = self._resolve_font_path(self.ui_font_family or self.ui_font_name)
        fallback_font_raw = config.get('Appearance', 'fallback_font_path', fallback=self.fallback_font_path).strip()
        self.fallback_font_path = os.path.expanduser(os.path.expandvars(fallback_font_raw)) if fallback_font_raw else ""
        self.ui_font_cache.clear()
        self.ui_font_debug_logged.clear()

        # Apply configured values from the configuration file with fallbacks
        
        # Appearance
        self.icon_size = config.getint('Appearance', 'icon_size', fallback=64)
        self.label_bg = get_color('Appearance', 'label_bg_color', (0, 0, 0, 0))
        self.hover_bg = get_color('Appearance', 'hover_bg_color', theme_select_bg or (0, 102, 204, 220))
        self.selection_bg = get_color('Appearance', 'selection_bg_color', theme_select_bg or (0, 102, 204, 255))
        self.text_hover = get_color('Appearance', 'label_text_color_hover', theme_select_fg or (255, 255, 255, 255))
        self.text_selected = get_color('Appearance', 'label_text_color_selected', theme_select_fg or (255, 255, 255, 255))
        self.text_normal = get_color('Appearance', 'label_text_color_normal', (255, 255, 255, 255))
        self.tooltip_bg = get_color('Appearance', 'tooltip_bg_color', (255, 255, 200, 255))
        
        # Layout
        self.spacing_x = config.getint('Layout', 'grid_spacing_x', fallback=140)
        self.spacing_y = config.getint('Layout', 'grid_spacing_y', fallback=180)
        self.grid_direction = config.get('Layout', 'grid_direction', fallback='vertical').strip().lower()
        if self.grid_direction not in ('vertical', 'horizontal'):
            self.grid_direction = 'vertical'
        self.grid_wrap_count = max(0, config.getint('Layout', 'grid_wrap_count', fallback=0))
        self.start_offset_x = config.getint('Layout', 'start_offset_x', fallback=50)
        self.start_offset_y = config.getint('Layout', 'start_offset_y', fallback=50)
        self.snap_grid_x = config.getint('Layout', 'snap_grid_x', fallback=self.spacing_x)
        self.snap_grid_y = config.getint('Layout', 'snap_grid_y', fallback=self.spacing_y)
        self.snap_origin_x = config.getint('Layout', 'snap_origin_x', fallback=self.start_offset_x)
        self.snap_origin_y = config.getint('Layout', 'snap_origin_y', fallback=self.start_offset_y)
        
        # Behavior
        self.tooltip_delay = config.getfloat('Behavior', 'tooltip_delay', fallback=1.5)
        self.double_click_timeout = config.getfloat('Behavior', 'double_click_timeout', fallback=0.3)
        self.snap_to_grid = config.getboolean('Behavior', 'snap_to_grid', fallback=True)
        self.snap_avoid_overlap = config.getboolean('Behavior', 'snap_avoid_overlap', fallback=True)
        self.layer_name = config.get('Behavior', 'layer', fallback='bottom').strip().lower()
        if not self.positions_path_locked:
            configured_positions = config.get('Behavior', 'positions_file', fallback=self.positions_path).strip()
            self.positions_path = os.path.expanduser(os.path.expandvars(configured_positions))
        else:
            self.positions_path = os.path.expanduser(os.path.expandvars(self.positions_path))
        if self.input_debug:
            print(
                f"🔤 UI-Font: name='{self.ui_font_name or 'n/a'}' "
                f"family='{self.ui_font_family or 'n/a'}' path='{self.ui_font_path or 'fallback'}' "
                f"fallback='{self.fallback_font_path or 'PillowDefault'}'"
            )
        print("⚙️ Konfiguration geladen.")

    def _extract_hex_color(self, value):
        """
        Extracts a hex color from a GTK CSS expression.
        
        Parameters
        ----------
        value : str
            Raw value from GTK CSS.
        
        Returns
        -------
        str | None:
            Hex color code (e.g. "#4a90d9") or None.
        """
        if not value:
            return None

        match = re.search(r"#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})", value)
        if match:
            return match.group(0)
        return None

    def _hex_to_rgba(self, hex_color, alpha=255):
        """
        Converts "#RRGGBB"/"#RRGGBBAA" to an RGBA tuple.
        
        Parameters
        ----------
        hex_color : str
            Hex color code.
        
        alpha : int
            Fallback alpha for "#RRGGBB".
        
        Returns
        -------
        tuple[int, int, int, int] | None:
            RGBA or None on error.
        """
        if not hex_color:
            return None

        value = hex_color.strip().lstrip('#')
        try:
            if len(value) == 6:
                red = int(value[0:2], 16)
                green = int(value[2:4], 16)
                blue = int(value[4:6], 16)
                return (red, green, blue, alpha)
            if len(value) == 8:
                red = int(value[0:2], 16)
                green = int(value[2:4], 16)
                blue = int(value[4:6], 16)
                alpha_value = int(value[6:8], 16)
                return (red, green, blue, alpha_value)
        except ValueError:
            return None
        return None

    def _read_gtk_theme_name_from_file(self, settings_path):
        """
        Reads the GTK theme name from a settings.ini.
        
        Parameters
        ----------
        settings_path : str
            Path to GTK settings.ini.
        
        Returns
        -------
        str | None:
            Theme name or None.
        """
        if not os.path.exists(settings_path):
            return None

        parser = configparser.ConfigParser()
        try:
            parser.read(settings_path, encoding="utf-8")
            if parser.has_option("Settings", "gtk-theme-name"):
                value = parser.get("Settings", "gtk-theme-name", fallback="").strip()
                return value or None
        except Exception:
            return None
        return None

    def _read_gtk_font_name_from_file(self, settings_path):
        """
        Reads the GTK font name from a settings.ini.
        
        Parameters
        ----------
        settings_path : str
            Path to GTK settings.ini.
        
        Returns
        -------
        str | None:
            Font name (e.g. "Noto Sans 10") or None.
        """
        if not os.path.exists(settings_path):
            return None

        parser = configparser.ConfigParser()
        try:
            parser.read(settings_path, encoding="utf-8")
            if parser.has_option("Settings", "gtk-font-name"):
                value = parser.get("Settings", "gtk-font-name", fallback="").strip()
                return value or None
        except Exception:
            return None
        return None

    def _read_gsettings_gtk_theme(self):
        """
        Reads the GTK theme name via gsettings.
        
        Returns
        -------
        str | None:
            Theme name or None.
        """
        if shutil.which("gsettings") is None:
            return None

        try:
            result = subprocess.run(
                ["gsettings", "get", "org.gnome.desktop.interface", "gtk-theme"],
                capture_output=True,
                text=True,
                timeout=0.6,
                check=False,
            )
        except Exception:
            return None

        if result.returncode != 0:
            return None

        raw = (result.stdout or "").strip()
        if raw.startswith("'") and raw.endswith("'") and len(raw) >= 2:
            raw = raw[1:-1]
        raw = raw.strip()
        return raw or None

    def _read_gsettings_gtk_font(self):
        """
        Reads the GTK font name via gsettings.
        
        Returns
        -------
        str | None:
            Font name or None.
        """
        if shutil.which("gsettings") is None:
            return None

        try:
            result = subprocess.run(
                ["gsettings", "get", "org.gnome.desktop.interface", "font-name"],
                capture_output=True,
                text=True,
                timeout=0.6,
                check=False,
            )
        except Exception:
            return None

        if result.returncode != 0:
            return None

        raw = (result.stdout or "").strip()
        if raw.startswith("'") and raw.endswith("'") and len(raw) >= 2:
            raw = raw[1:-1]
        raw = raw.strip()
        return raw or None

    def get_active_gtk_theme(self):
        """
        Determines the active GTK theme.
        
        Returns
        -------
        str | None:
            Theme name or None.
        """
        env_theme = os.environ.get("GTK_THEME", "").strip()
        if env_theme:
            return env_theme.split(":", 1)[0].strip() or None

        gtk3_theme = self._read_gtk_theme_name_from_file(os.path.expanduser("~/.config/gtk-3.0/settings.ini"))
        if gtk3_theme:
            return gtk3_theme

        gtk4_theme = self._read_gtk_theme_name_from_file(os.path.expanduser("~/.config/gtk-4.0/settings.ini"))
        if gtk4_theme:
            return gtk4_theme

        return self._read_gsettings_gtk_theme()

    def get_active_gtk_font_name(self):
        """
        Determines the active GTK UI font.
        
        Returns
        -------
        str | None:
            Font name (including optional size), e.g. "Cantarell 11".
        """
        env_font = os.environ.get("GTK_FONT_NAME", "").strip()
        if env_font:
            return env_font

        gtk3_font = self._read_gtk_font_name_from_file(os.path.expanduser("~/.config/gtk-3.0/settings.ini"))
        if gtk3_font:
            return gtk3_font

        gtk4_font = self._read_gtk_font_name_from_file(os.path.expanduser("~/.config/gtk-4.0/settings.ini"))
        if gtk4_font:
            return gtk4_font

        return self._read_gsettings_gtk_font()

    def _split_gtk_font_name(self, font_name):
        """
        Splits GTK font string into family and point size.
        
        Parameters
        ----------
        font_name : str
            Font string like "Noto Sans 10".
        
        Returns
        -------
        tuple[str, float]:
            Family/style and point size.
        """
        if not font_name:
            return "", 10.0

        value = font_name.strip()
        match = re.match(r"^(.*?)(?:\s+(\d+(?:\.\d+)?))?$", value)
        if not match:
            return value, 10.0

        family = (match.group(1) or "").strip()
        size_raw = (match.group(2) or "").strip()

        try:
            size_value = float(size_raw) if size_raw else 10.0
        except ValueError:
            size_value = 10.0

        return family or value, size_value

    def _resolve_font_path(self, font_query):
        """
        Resolves a font family via fontconfig to a TTF/OTF path.
        
        Parameters
        ----------
        font_query : str
            Font family or pattern.
        
        Returns
        -------
        str | None:
            File path to the font file or None.
        """
        if not font_query or shutil.which("fc-match") is None:
            return None

        try:
            result = subprocess.run(
                ["fc-match", "-f", "%{file}", font_query],
                capture_output=True,
                text=True,
                timeout=0.6,
                check=False,
            )
        except Exception:
            return None

        if result.returncode != 0:
            return None

        candidate = (result.stdout or "").strip()
        if candidate and os.path.exists(candidate):
            return candidate
        return None

    def get_ui_font(self, pixel_size):
        """
        Loads the UI font, preferably from the active GTK theme.
        
        Parameters
        ----------
        pixel_size : int
            Target size in pixels.
        
        Returns
        -------
        ImageFont.FreeTypeFont | ImageFont.ImageFont:
            Loaded font.
        """
        size = max(8, int(pixel_size))
        font_key = f"{self.ui_font_path or 'theme-none'}|{self.fallback_font_path or 'fallback-none'}@{size}"
        cached_font = self.ui_font_cache.get(font_key)
        if cached_font is not None:
            return cached_font

        resolved_source = self.ui_font_path
        loaded_font = None

        if self.ui_font_path:
            try:
                loaded_font = ImageFont.truetype(self.ui_font_path, size)
            except Exception:
                loaded_font = None

        if loaded_font is None:
            fallback_path = self.fallback_font_path
            if fallback_path:
                try:
                    loaded_font = ImageFont.truetype(fallback_path, size)
                    resolved_source = fallback_path
                except Exception:
                    loaded_font = None

        if loaded_font is None:
            loaded_font = ImageFont.load_default()
            resolved_source = "PillowDefault"

        self.ui_font_cache[font_key] = loaded_font

        if self.input_debug and font_key not in self.ui_font_debug_logged:
            print(f"🔤 Font geladen: source='{resolved_source}' size={size}px")
            self.ui_font_debug_logged.add(font_key)

        return loaded_font

    def get_theme_selection_colors(self):
        """
        Reads selection colors from the active GTK theme CSS.
        
        Returns
        -------
        tuple[tuple[int, int, int, int] | None, tuple[int, int, int, int] | None]:
            Background and text color for selection/hover.
        """
        theme_name = self.get_active_gtk_theme()
        if not theme_name:
            return None, None

        theme_paths = [
            os.path.expanduser(f"~/.themes/{theme_name}/gtk-3.0/gtk.css"),
            os.path.expanduser(f"~/.local/share/themes/{theme_name}/gtk-3.0/gtk.css"),
            f"/usr/share/themes/{theme_name}/gtk-3.0/gtk.css",
            f"/usr/share/themes/{theme_name}/gtk-4.0/gtk.css",
        ]

        bg_names = ["theme_selected_bg_color", "selected_bg_color", "accent_bg_color"]
        fg_names = ["theme_selected_fg_color", "selected_fg_color", "accent_fg_color"]
        bg_rgba = None
        fg_rgba = None

        for css_path in theme_paths:
            if not os.path.exists(css_path):
                continue
            try:
                with open(css_path, "r", encoding="utf-8", errors="ignore") as file_obj:
                    content = file_obj.read()
            except Exception:
                continue

            if bg_rgba is None:
                for name in bg_names:
                    match = re.search(rf"@define-color\s+{re.escape(name)}\s+([^;]+);", content)
                    if not match:
                        continue
                    hex_color = self._extract_hex_color(match.group(1))
                    bg_rgba = self._hex_to_rgba(hex_color, alpha=220)
                    if bg_rgba is not None:
                        break

            if fg_rgba is None:
                for name in fg_names:
                    match = re.search(rf"@define-color\s+{re.escape(name)}\s+([^;]+);", content)
                    if not match:
                        continue
                    hex_color = self._extract_hex_color(match.group(1))
                    fg_rgba = self._hex_to_rgba(hex_color, alpha=255)
                    if fg_rgba is not None:
                        break

            if bg_rgba is not None and fg_rgba is not None:
                break

        if self.input_debug and (bg_rgba or fg_rgba):
            print(f"🎨 GTK Selection-Farben: bg={bg_rgba} fg={fg_rgba}")

        return bg_rgba, fg_rgba

    def load_icon_positions(self):
        """
        Loads saved icon positions from JSON.
        """
        self.icon_positions = {}
        try:
            if not os.path.exists(self.positions_path):
                return
            with open(self.positions_path, 'r', encoding='utf-8') as file_obj:
                data = json.load(file_obj)
            if not isinstance(data, dict):
                return
            normalized: dict[str, dict[str, int]] = {}
            for key, value in data.items():
                if not isinstance(value, dict):
                    continue
                x_val = value.get('x')
                y_val = value.get('y')
                if isinstance(x_val, (int, float)) and isinstance(y_val, (int, float)):
                    normalized[str(key)] = {'x': int(x_val), 'y': int(y_val)}
            self.icon_positions = normalized
        except Exception as error:
            print(f"⚠️ Konnte Icon-Positionen nicht laden: {error}")

    def save_icon_positions(self):
        """
        Saves current icon positions to a JSON file.
        """
        try:
            os.makedirs(os.path.dirname(self.positions_path), exist_ok=True)
            positions: dict[str, dict[str, int]] = {}
            for icon in self.icons:
                icon_key = self._icon_key(icon)
                positions[icon_key] = {'x': int(icon['x']), 'y': int(icon['y'])}
            with open(self.positions_path, 'w', encoding='utf-8') as file_obj:
                json.dump(positions, file_obj, ensure_ascii=False, indent=2)
            self.icon_positions = positions
        except Exception as error:
            print(f"⚠️ Konnte Icon-Positionen nicht speichern: {error}")

    def _icon_key(self, icon):
        """
        Returns a stable key for persistent icon positions.
        
        Parameters
        ----------
        icon : dict
            Icon record.
        
        Returns
        -------
        str:
            Key for position mapping.
        """
        return str(icon.get('path') or icon.get('filename') or icon.get('name', ''))

    def check_config_reload(self):
        """
        Checks for configuration file changes.
        """
        if os.path.exists(self.config_path):
            current_mtime = os.path.getmtime(self.config_path)
            if current_mtime > self.last_config_mtime:
                self.last_config_mtime = current_mtime
                self.load_config()
                self.load_icon_positions()
                self.load_desktop_entries()
                self.refresh_desktop()

    def check_desktop_reload(self):
        """
        Checks for changes in the desktop directory.
        """
        if os.path.exists(self.desktop_path):
            current_mtime = os.path.getmtime(self.desktop_path)
            if current_mtime > self.last_desktop_mtime:
                self.last_desktop_mtime = current_mtime
                self.load_desktop_entries() 
                self.refresh_desktop()

    # --- Wayland: Registry / Output / Surface ---
    def _registry_global_handler(self, registry, id, interface, version):
        """
        Binds required Wayland globals from the registry and sets dispatchers.
        
        Parameters
        ----------
        registry : object
            Wayland registry object.
        
        id : int
            Global object ID of the interface.
        
        interface : str
            Name of the Wayland interface.
        
        version : int
            Supported protocol version.
        """
        if interface == "zwlr_layer_shell_v1":
            self.layer_shell = registry.bind(id, ZwlrLayerShellV1, version)
        elif interface == "wl_compositor":
            self.compositor = registry.bind(id, WlCompositor, version)
        elif interface == "wl_shm":
            self.shm = registry.bind(id, WlShm, version)
        elif interface == "wl_seat":
            self.seat = registry.bind(id, WlSeat, version)
            self.seat.dispatcher['capabilities'] = self._on_seat_capabilities
        elif interface == "wl_output":
            output = registry.bind(id, WlOutput, version)
            output.dispatcher['mode'] = self._on_output_mode
            output.dispatcher['scale'] = self._on_output_scale
            self.outputs.append(output)

    def _on_seat_capabilities(self, seat, capabilities):
        """
        Reacts to seat capabilities and initializes the pointer if needed.
        
        Parameters
        ----------
        seat : object
            Wayland seat object.
        
        capabilities : int
            Bitmask of active input capabilities.
        """
        has_pointer = bool(capabilities & int(WlSeat.capability.pointer))
        if self.input_debug:
            print(f"🖱️ Seat capabilities: {capabilities} (pointer={has_pointer})")

        if has_pointer and self.pointer is None:
            self.setup_pointer()
        elif not has_pointer and self.pointer is not None:
            try:
                self.pointer.release()
            except Exception:
                pass
            self.pointer = None
            if self.hover_index != -1:
                self.hover_index = -1
                self.tooltip_visible = False
                self.refresh_desktop()

    def _on_output_mode(self, output, flags, width, height, refresh):
        """
        Updates resolution on preferred output mode and re-renders.
        
        Parameters
        ----------
        output : object
            Wayland output object.
        
        flags : int
            Bitmask for mode properties.
        
        width : int
            Width of the output in pixels.
        
        height : int
            Height of the output in pixels.
        
        refresh : int
            Refresh rate of the output.
        """
        if flags & 0x1:
            self.width, self.height = width, height
            if self.icons: self.refresh_desktop()

    def _on_output_scale(self, output, factor):
        """
        Applies the output scaling factor and sets it on the surface.
        
        Parameters
        ----------
        output : object
            Wayland output object.
        
        factor : int
            Scaling factor for HiDPI.
        """
        self.scale = factor
        if self.surface: self.surface.set_buffer_scale(factor)

    def setup_desktop_surface(self):
        """
        Creates and configures the layer surface for desktop icons.
        """
        layer_map = {
            'background': int(ZwlrLayerShellV1.layer.background),
            'bottom': int(ZwlrLayerShellV1.layer.bottom),
            'top': int(ZwlrLayerShellV1.layer.top),
            'overlay': int(ZwlrLayerShellV1.layer.overlay),
        }
        layer_value = layer_map.get(self.layer_name, int(ZwlrLayerShellV1.layer.top))
        self.surface = self.compositor.create_surface()
        self.layer_surface = self.layer_shell.get_layer_surface(self.surface, None, layer_value, "desktop_icons")
        # The dispatcher waits for confirmation (configure event) from the server
        self.layer_surface.dispatcher['configure'] = self._on_layer_surface_configure
        
        # Set anchor (top-left = 3, or 15 for the full screen)
        self.layer_surface.set_anchor(15) 
        
        # Do not allow keyboard/mouse interaction
        self.layer_surface.set_keyboard_interactivity(0)
        
        self.layer_surface.set_size(self.width, self.height)
        # IMPORTANT: First commit signals to the server: "I am ready for configure"
        self.surface.commit()
        self.display.flush()

    def _on_layer_surface_configure(self, layer_surface, serial, width, height):
        """
        Processes the configure event of the layer surface.
        
        Parameters
        ----------
        layer_surface : object
            Wayland layer surface object.
        
        serial : int
            Configure serial for acknowledgment.
        
        width : int
            Width confirmed by the server.
        
        height : int
            Height confirmed by the server.
        """
        layer_surface.ack_configure(serial)

        size_changed = (width != self.width) or (height != self.height)
        first_configure = not self.configured

        self.width = width
        self.height = height
        self.configured = True

        if not first_configure and not size_changed:
            return
        
        # Recalculate icons now that we know the actual size
        self.load_desktop_entries() 
        
        print(f"✅ Surface konfiguriert: {width}x{height}")
        # Only now, when everything is ready, draw for the first time
        self.refresh_desktop()

    # --- Icons / Desktop Entries ---
    def _read_gtk_icon_theme_from_file(self, settings_path):
        """
        Reads the icon theme name from a GTK settings.ini.
        
        Parameters
        ----------
        settings_path : str
            Path to GTK settings.ini.
        
        Returns
        -------
        str | None:
            Theme name or None.
        """
        if not os.path.exists(settings_path):
            return None

        parser = configparser.ConfigParser()
        try:
            parser.read(settings_path, encoding="utf-8")
            if parser.has_option("Settings", "gtk-icon-theme-name"):
                value = parser.get("Settings", "gtk-icon-theme-name", fallback="").strip()
                return value or None
        except Exception:
            return None
        return None

    def _read_gsettings_icon_theme(self):
        """
        Reads the icon theme name via gsettings (if available).
        
        Returns
        -------
        str | None:
            Theme name or None.
        """
        if shutil.which("gsettings") is None:
            return None

        try:
            result = subprocess.run(
                ["gsettings", "get", "org.gnome.desktop.interface", "icon-theme"],
                capture_output=True,
                text=True,
                timeout=0.6,
                check=False,
            )
        except Exception:
            return None

        if result.returncode != 0:
            return None

        raw = (result.stdout or "").strip()
        if raw.startswith("'") and raw.endswith("'") and len(raw) >= 2:
            raw = raw[1:-1]
        raw = raw.strip()
        return raw or None

    def get_active_icon_themes(self, *, force_refresh=False):
        """
        Determines active user icon themes (with fallback order).
        
        Parameters
        ----------
        force_refresh : bool
            Forces re-evaluation instead of using cache.
        
        Returns
        -------
        list[str]:
            Theme order, first element = preferred.
        """
        if self.active_icon_themes and not force_refresh:
            return self.active_icon_themes

        candidates = []

        env_theme = os.environ.get(
            "ldicons_ICON_THEME",
            os.environ.get("PYDICONS_ICON_THEME", os.environ.get("DICONS_ICON_THEME", "")),
        ).strip()
        if env_theme:
            candidates.append(env_theme)

        gtk3_theme = self._read_gtk_icon_theme_from_file(os.path.expanduser("~/.config/gtk-3.0/settings.ini"))
        if gtk3_theme:
            candidates.append(gtk3_theme)

        gtk4_theme = self._read_gtk_icon_theme_from_file(os.path.expanduser("~/.config/gtk-4.0/settings.ini"))
        if gtk4_theme:
            candidates.append(gtk4_theme)

        gsettings_theme = self._read_gsettings_icon_theme()
        if gsettings_theme:
            candidates.append(gsettings_theme)

        candidates.extend(["hicolor", "Adwaita"])

        unique = []
        seen = set()
        for name in candidates:
            clean = (name or "").strip()
            if not clean:
                continue
            key = clean.lower()
            if key in seen:
                continue
            seen.add(key)
            unique.append(clean)

        self.active_icon_themes = unique
        if self.input_debug:
            print(f"🎨 Aktive Icon-Themes: {', '.join(self.active_icon_themes)}")
        return self.active_icon_themes

    def find_icon(self, icon_name, *, use_fallback=True):
        """
        Searches for an icon using XDG standard paths.
        
        Parameters
        ----------
        icon_name : str
            Name or absolute path of the icon.
        
        use_fallback : bool
            Beschreibung.
        
        Returns
        -------
        str | None:
            Found icon path or fallback/None.
        """
        
        if not icon_name:
            return self.get_fallback_icon() if use_fallback else None

        if icon_name.startswith("/"):
            if os.path.exists(icon_name):
                return icon_name
            return self.get_fallback_icon() if use_fallback else None

        # Define XDG paths
        xdg_data_home = os.environ.get('XDG_DATA_HOME', os.path.expanduser("~/.local/share"))
        xdg_data_dirs = os.environ.get('XDG_DATA_DIRS', "/usr/local/share:/usr/share").split(':')

        # Treat theme roots separately from flat pixmap roots,
        # so scalable theme icons clearly get priority.
        icon_roots = [os.path.join(xdg_data_home, "icons")]
        pixmap_roots = []
        for d in xdg_data_dirs:
            icon_roots.append(os.path.join(d, "icons"))
            pixmap_roots.append(os.path.join(d, "pixmaps"))

        svg_extensions = [".svg"]
        raster_extensions = [".png", ".xpm"]

        # Keep theme paths intentionally small: active user theme + slim fallback
        themes = self.get_active_icon_themes()
        sizes = [
            f"{self.icon_size}x{self.icon_size}",
            "64x64", "48x48", "32x32", "24x24", "22x22", "16x16",
        ]
        categories = ["apps", "mimetypes", "places", "status", "devices", "actions", "categories"]

        scalable_subdirs = []
        sized_subdirs = []
        for theme in themes:
            for category in categories:
                scalable_subdirs.append(f"{theme}/scalable/{category}")
                for size in sizes:
                    sized_subdirs.append(f"{theme}/{size}/{category}")

        def _find_in_roots(roots, subdirs, exts):
            for root in roots:
                if not os.path.exists(root):
                    continue
                for subdir in subdirs:
                    for ext in exts:
                        path = os.path.join(root, subdir, icon_name + ext)
                        if os.path.exists(path):
                            return path
            return None

        # 1) First scalable theme icons (SVG)
        found = _find_in_roots(icon_roots, scalable_subdirs, svg_extensions)
        if found:
            if self.input_debug:
                print(f"🖼️ Icon gefunden (scalable svg): {icon_name} -> {found}")
            return found

        # 2) Then SVG in size subdirectories
        found = _find_in_roots(icon_roots, sized_subdirs, svg_extensions)
        if found:
            if self.input_debug:
                print(f"🖼️ Icon gefunden (sized svg): {icon_name} -> {found}")
            return found

        # 3) Then raster icons in theme paths
        found = _find_in_roots(icon_roots, scalable_subdirs + sized_subdirs, raster_extensions)
        if found:
            if self.input_debug:
                print(f"🖼️ Icon gefunden (theme raster): {icon_name} -> {found}")
            return found

        # 4) Finally direct file names (root/pixmaps)
        direct_roots = icon_roots + pixmap_roots
        for root in direct_roots:
            if not os.path.exists(root):
                continue

            direct_named = os.path.join(root, icon_name)
            if os.path.exists(direct_named):
                if self.input_debug:
                    print(f"🖼️ Icon gefunden (direct named): {icon_name} -> {direct_named}")
                return direct_named

            for ext in svg_extensions + raster_extensions:
                direct_path = os.path.join(root, icon_name + ext)
                if os.path.exists(direct_path):
                    if self.input_debug:
                        print(f"🖼️ Icon gefunden (direct ext): {icon_name} -> {direct_path}")
                    return direct_path

        fallback = self.get_fallback_icon() if use_fallback else None
        if self.input_debug:
            print(f"❓ Icon nicht gefunden: {icon_name} -> {fallback}")
        return fallback

    def get_fallback_icon(self):
        """
        Returns the path to the local fallback icon.
        
        Returns
        -------
        str | None:
            Path to the fallback icon or None.
        """
        # [...] (XDG_DATA_HOME and XDG_DATA_DIRS as discussed)
        # Addition for global installation of your own icons:
        # search_roots.append("/usr/share/ldicons") 
    
        # Not-Found Fallback
        local_fallback = os.path.join(os.path.dirname(__file__), "Not-Found-Icon.svg")
        if os.path.exists(local_fallback):
            return local_fallback
        return None # Last resort: No icon available    
    
    def parse_desktop_file(self, filepath):
        """
        Reads a .desktop file and extracts metadata.
        
        Parameters
        ----------
        filepath : str
            Path to the ".desktop" file.
        
        Returns
        -------
        dict | None:
            Icon data or None on errors.
        """
        config = configparser.ConfigParser(interpolation=None)
        try:
            config.read(filepath, encoding='utf-8')
            section = 'Desktop Entry'
            if section not in config:
                return None

            entry = config[section]
            localized_name, name_key = self._get_localized_desktop_value(entry, 'Name')
            localized_comment, comment_key = self._get_localized_desktop_value(entry, 'Comment')
            localized_generic_name, generic_name_key = self._get_localized_desktop_value(entry, 'GenericName')

            tooltip_text = (
                localized_comment
                or localized_generic_name
                or localized_name
                or os.path.splitext(os.path.basename(filepath))[0]
            )
            if self.input_debug:
                print(
                    f"🌐 Locale-Match {os.path.basename(filepath)}: "
                    f"Name={name_key}, Comment={comment_key}, GenericName={generic_name_key}"
                )
            return {
                'name': localized_name if localized_name else os.path.basename(filepath),
                'exec': config.get(section, 'Exec', fallback=''),
                'comment': tooltip_text,
                'icon_path': self.find_icon(config.get(section, 'Icon', fallback='')),
                'path': filepath
            }
        except: return None

    def _get_preferred_locales(self):
        """
        Determines preferred locale codes in priority order.
        
        Returns
        -------
        list[str]:
            List of normalized locale codes (e.g. "de_de", "de").
        """
        tokens = []

        language_env = os.environ.get('LANGUAGE', '')
        if language_env:
            tokens.extend([token.strip() for token in language_env.split(':') if token.strip()])

        for env_name in ('LC_ALL', 'LC_MESSAGES', 'LANG'):
            value = os.environ.get(env_name, '').strip()
            if value:
                tokens.append(value)

        try:
            locale_value = locale.getlocale()[0]
            if locale_value:
                tokens.append(locale_value)
        except Exception:
            pass

        normalized = []
        seen = set()

        for token in tokens:
            clean = token.split('.', 1)[0].split('@', 1)[0].replace('-', '_').strip().lower()
            if not clean:
                continue

            variants = [clean]
            if '_' in clean:
                variants.append(clean.split('_', 1)[0])

            for variant in variants:
                if variant and variant not in seen:
                    seen.add(variant)
                    normalized.append(variant)

        return normalized

    def _get_localized_desktop_value(self, entry, key_base):
        """
        Reads a localized .desktop value with fallback.
        
        Parameters
        ----------
        entry : configparser.SectionProxy
            "Desktop Entry" section as mapping.
        
        key_base : str
            Base key name (e.g. "Comment" or "Name").
        
        Returns
        -------
        tuple[str, str]:
            Tuple of value and the actually used key.
        """
        options = {str(key).lower(): value for key, value in entry.items()}
        base_key = key_base.lower()

        for locale_code in self._get_preferred_locales():
            localized_key = f"{base_key}[{locale_code}]"
            value = options.get(localized_key)
            if value:
                return value, localized_key

        fallback_value = options.get(base_key, '')
        if fallback_value:
            return fallback_value, base_key
        return '', 'missing'

    def get_info_for_generic_file(self, filepath):
        """
        Determines representation and launch command for regular files/folders.
        
        Parameters
        ----------
        filepath : str
            Path to the file or folder.
        
        Returns
        -------
        dict:
            Icon data including name, comment, and launch command.
        """
        filename = os.path.basename(filepath)
        if os.path.isdir(filepath):
            folder_icon = (
                self.find_icon("folder", use_fallback=False)
                or self.find_icon("inode-directory", use_fallback=False)
                or self.find_icon("folder-documents", use_fallback=False)
                or self.find_icon("folder")
            )
            return {
                'name': filename, 'exec': f"pcmanfm '{filepath}'",
                'comment': "Ordner", 'icon_path': folder_icon, 'path': filepath
            }
        mime, _ = mimetypes.guess_type(filepath)

        icon_candidates = []
        if mime:
            full_mime_icon = mime.replace('/', '-')
            major_mime_icon = f"{mime.split('/', 1)[0]}-x-generic"

            # First content-specific generic icons, then concrete MIME icons.
            if mime.startswith('image/'):
                icon_candidates.extend(["image-x-generic", "x-office-drawing", full_mime_icon, major_mime_icon])
            elif mime.startswith('video/'):
                icon_candidates.extend(["video-x-generic", "video", full_mime_icon, major_mime_icon])
            elif mime.startswith('audio/'):
                icon_candidates.extend(["audio-x-generic", "audio", full_mime_icon, major_mime_icon])
            elif mime.startswith('text/'):
                icon_candidates.extend(["text-x-generic", "x-office-document", full_mime_icon, major_mime_icon])
            elif mime == 'application/pdf':
                icon_candidates.extend(["application-pdf", "document-pdf", "x-office-document", full_mime_icon, major_mime_icon])
            elif mime in ('application/zip', 'application/x-zip-compressed'):
                icon_candidates.extend(["package-x-generic", "application-zip", full_mime_icon, major_mime_icon])
            elif mime in ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/msword'):
                icon_candidates.extend(["x-office-document", "application-msword", full_mime_icon, major_mime_icon])
            elif mime in ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel'):
                icon_candidates.extend(["x-office-spreadsheet", "application-vnd.ms-excel", full_mime_icon, major_mime_icon])
            else:
                icon_candidates.extend([full_mime_icon, major_mime_icon])

        # Hard fallbacks only at the end.
        icon_candidates.extend(["text-x-generic", "unknown", "application-octet-stream"])

        seen = set()
        icon_path = None
        for candidate in icon_candidates:
            if not candidate or candidate in seen:
                continue
            seen.add(candidate)
            icon_path = self.find_icon(candidate, use_fallback=False)
            if icon_path:
                break

        if not icon_path:
            icon_path = self.find_icon("text-x-generic")

        return {
            'name': filename, 'exec': f"xdg-open '{filepath}'",
            'comment': mime if mime else "Datei", 'icon_path': icon_path, 'path': filepath
        }

    def _update_icon_hitboxes(self, icon):
        """
        Recalculates icon and text hitbox for a single icon.
        
        Parameters
        ----------
        icon : dict
            Icon record with position in "x"/"y".
        """
        icon_size = self.icon_size
        event_area_size = icon_size + 2
        text_width = int(icon_size * 1.1875)
        text_height = int(icon_size * 0.9)
        padding = 1

        x = int(icon['x'])
        y = int(icon['y'])

        icon['icon_rect'] = [
            x - padding,
            y - padding,
            event_area_size + (2 * padding),
            event_area_size + (2 * padding),
        ]
        icon['text_rect'] = [
            x + (icon_size // 2) - (text_width // 2),
            y + event_area_size,
            text_width,
            text_height,
        ]

    def _snap_icon_to_grid(self, icon):
        """
        Snaps an icon to the configured grid.
        
        Parameters
        ----------
        icon : dict
            Icon record with "x"/"y" position.
        """
        if not self.snap_to_grid:
            return

        step_x = max(1, int(self.snap_grid_x))
        step_y = max(1, int(self.snap_grid_y))
        origin_x = int(self.snap_origin_x)
        origin_y = int(self.snap_origin_y)

        curr_x = float(icon['x'])
        curr_y = float(icon['y'])

        target_cx = round((curr_x - origin_x) / step_x)
        target_cy = round((curr_y - origin_y) / step_y)

        max_x = max(0, self.width - self.icon_size)
        max_y = max(0, self.height - self.icon_size)

        def cell_to_pos(cell_x, cell_y):
            return (origin_x + (cell_x * step_x), origin_y + (cell_y * step_y))

        def is_in_bounds(cell_x, cell_y):
            px, py = cell_to_pos(cell_x, cell_y)
            return 0 <= px <= max_x and 0 <= py <= max_y

        occupied = set()
        if self.snap_avoid_overlap:
            for other_icon in self.icons:
                if other_icon is icon:
                    continue
                ox = float(other_icon.get('x', 0))
                oy = float(other_icon.get('y', 0))
                ocx = round((ox - origin_x) / step_x)
                ocy = round((oy - origin_y) / step_y)
                occupied.add((ocx, ocy))

        chosen_cell = (target_cx, target_cy)

        if self.snap_avoid_overlap and ((chosen_cell in occupied) or (not is_in_bounds(*chosen_cell))):
            max_radius = int(
                ((max_x + step_x) / step_x) +
                ((max_y + step_y) / step_y) + 4
            )
            found = False

            for radius in range(1, max_radius):
                candidates = []
                for dx in range(-radius, radius + 1):
                    for dy in range(-radius, radius + 1):
                        if max(abs(dx), abs(dy)) != radius:
                            continue
                        cx = target_cx + dx
                        cy = target_cy + dy
                        candidates.append((cx, cy, abs(dx) + abs(dy), abs(dy), abs(dx)))

                candidates.sort(key=lambda item: (item[2], item[3], item[4]))

                for cx, cy, _, _, _ in candidates:
                    if not is_in_bounds(cx, cy):
                        continue
                    if (cx, cy) in occupied:
                        continue
                    chosen_cell = (cx, cy)
                    found = True
                    break

                if found:
                    break

        snapped_x, snapped_y = cell_to_pos(*chosen_cell)
        icon['x'] = max(0, min(int(snapped_x), max_x))
        icon['y'] = max(0, min(int(snapped_y), max_y))
        self._update_icon_hitboxes(icon)

    def load_desktop_entries(self):
        """
        Loads desktop entries and calculates hitboxes for icon and text.
        """
        if not os.path.exists(self.desktop_path): return
        
        files = [f for f in os.listdir(self.desktop_path) if not f.startswith('.')]
        print(f"DEBUG: Gefundene Dateien: {files}")

        step_x = max(1, int(self.spacing_x))
        step_y = max(1, int(self.spacing_y))
        start_x = int(self.start_offset_x)
        start_y = int(self.start_offset_y)

        def rects_overlap(rect_a, rect_b):
            ax, ay, aw, ah = rect_a
            bx, by, bw, bh = rect_b
            return not (
                ax + aw <= bx or
                bx + bw <= ax or
                ay + ah <= by or
                by + bh <= ay
            )

        def collides(candidate_icon):
            for placed_icon in self.icons:
                if (
                    rects_overlap(candidate_icon['icon_rect'], placed_icon['icon_rect']) or
                    rects_overlap(candidate_icon['icon_rect'], placed_icon['text_rect']) or
                    rects_overlap(candidate_icon['text_rect'], placed_icon['icon_rect']) or
                    rects_overlap(candidate_icon['text_rect'], placed_icon['text_rect'])
                ):
                    return True
            return False

        def next_slot(slot_x, slot_y, run_count):
            margin_x = self.width - 100
            margin_y = self.height - 100
            wrap_after = self.grid_wrap_count
            force_wrap = wrap_after > 0 and run_count >= wrap_after

            if self.grid_direction == 'horizontal':
                next_x = slot_x + step_x
                next_y = slot_y
                if next_x > margin_x or force_wrap:
                    next_x = start_x
                    next_y += step_y
            else:
                next_x = slot_x
                next_y = slot_y + step_y
                if next_y > margin_y or force_wrap:
                    next_y = start_y
                    next_x += step_x
            return next_x, next_y

        def place_icon_without_overlap(icon_data, initial_x, initial_y):
            candidate_x = int(initial_x)
            candidate_y = int(initial_y)
            max_x = max(0, self.width - self.icon_size)
            max_y = max(0, self.height - self.icon_size)
            max_tries = max(200, len(files) * 20)

            for _ in range(max_tries):
                icon_data['x'] = max(0, min(candidate_x, max_x))
                icon_data['y'] = max(0, min(candidate_y, max_y))
                self._update_icon_hitboxes(icon_data)
                if not collides(icon_data):
                    return
                candidate_x, candidate_y = next_slot(candidate_x, candidate_y, 1)

            self._update_icon_hitboxes(icon_data)

        loaded_entries = []

        for filename in files:
            path = os.path.join(self.desktop_path, filename)
            is_desktop_file = filename.lower().endswith(".desktop")
            data = self.parse_desktop_file(path) if is_desktop_file else self.get_info_for_generic_file(path)
            if is_desktop_file and data is None:
                if self.input_debug:
                    print(f"⚠️ Konnte .desktop nicht parsen, nutze Fallback: {filename}")
                data = self.get_info_for_generic_file(path)
            
            if data:
                data.update({
                    'x': start_x, 'y': start_y,
                    'filename': filename
                })
                icon_key = self._icon_key(data)
                saved_pos = self.icon_positions.get(icon_key)
                loaded_entries.append((data, saved_pos))

        self.icons = []

        # 1) First apply saved positions (have priority)
        for data, saved_pos in loaded_entries:
            if not saved_pos:
                continue
            place_icon_without_overlap(data, int(saved_pos['x']), int(saved_pos['y']))
            self.icons.append(data)

        # 2) Then place new/unsaved icons on free grid slots
        slot_x, slot_y = start_x, start_y
        run_count = 0
        for data, saved_pos in loaded_entries:
            if saved_pos:
                continue
            place_icon_without_overlap(data, slot_x, slot_y)
            self.icons.append(data)
            run_count += 1
            slot_x, slot_y = next_slot(slot_x, slot_y, run_count)
            if self.grid_wrap_count > 0 and run_count >= self.grid_wrap_count:
                run_count = 0
                    
        # After all icons are loaded, send the region to Wayland
        self.update_wayland_input_region()

    # --- Input Regions ---
    def update_wayland_input_region(self):
        """
        Transfers precise icon/text hitboxes as a Wayland input region.
        """
        if not self.compositor or not self.surface:
            return
            
        region = self.compositor.create_region()

        for icon in self.icons:
            ix, iy, iw, ih = icon['icon_rect']
            tx, ty, tw, th = icon['text_rect']
            region.add(int(ix), int(iy), int(iw), int(ih))
            region.add(int(tx), int(ty), int(tw), int(th))
            
        self.surface.set_input_region(region)
        region.destroy()
        print(f"🎯 Input-Region für {len(self.icons)} Icons gesetzt.")

    def update_input_regions(self):
        """
        Updates input regions for icons, labels, and context menu.
        """
        if not self.compositor or not self.surface:
            return
    
        # Create new region
        region = self.compositor.create_region()

        if self.menu_visible or self.dragging_index != -1:
            # While the menu is open, receive events on the entire
            # surface so a click outside can close the menu.
            region.add(0, 0, int(self.width), int(self.height))
        else:
            for icon in self.icons:
                ix, iy, iw, ih = icon['icon_rect']
                tx, ty, tw, th = icon['text_rect']
                region.add(int(ix), int(iy), int(iw), int(ih))
                region.add(int(tx), int(ty), int(tw), int(th))

        # 2. Bind region to surface
        self.surface.set_input_region(region)
        
        # 3. Region object can then be destroyed
        region.destroy()
        print("🎯 Input-Regionen für Icons aktualisiert.")

    # --- Rendering ---
    def create_buffer(self, width, height):
        """
        Creates SHM buffer and mmap for drawing a frame.
        
        Parameters
        ----------
        width : int
            Buffer width in pixels.
        
        height : int
            Buffer height in pixels.
        
        Returns
        -------
        tuple:
            Tuple of Wayland buffer and mmap object.
        """
        stride = width * 4
        size = stride * height
        with tempfile.TemporaryFile(dir="/dev/shm") as tmp:
            tmp.truncate(size)
            mm = mmap.mmap(tmp.fileno(), size)
            pool = self.shm.create_pool(tmp.fileno(), size)
            buffer = pool.create_buffer(0, width, height, stride, 0)
            pool.destroy()
            return buffer, mm

    def draw_icon_with_label(self, mm, buffer_pixel_width, icon_info, is_hover, show_tooltip, scale, icon_index):
        """
        Renders an icon with label/tooltip into the mmap buffer.
        
        Parameters
        ----------
        mm : mmap.mmap
            Mmap buffer of the current frame.
        
        buffer_pixel_width : int
            Width of the target buffer in pixels.
        
        icon_info : dict
            Data of the icon to draw.
        
        is_hover : bool
            True if the icon is hovered.
        
        show_tooltip : bool
            True if tooltip should be drawn.
        
        scale : int
            Current output scaling factor.
        
        icon_index : int
            Index of the icon in the icon list.
        """
        # --- Dynamic calculation based on config (ISize) ---
        i_size = self.icon_size
        
        # Your formulas implemented in a universal way:
        event_area_size = i_size + 2
        text_width_base = i_size * 1.1875
        text_height_min = i_size * 0.46
        max_line_width = text_width_base * 0.79
    
        # Apply scaling for HiDPI/Wayland
        s_icon = int(i_size * scale)
        s_event = int(event_area_size * scale)
        s_text_w = int(text_width_base * scale)
        s_text_h_min = int(text_height_min * scale)
        s_max_line = int(max_line_width * scale)
        
        canvas_w = s_text_w
        
        # Font settings
        font = self.get_ui_font(int(10 * scale))
        tooltip_font = self.get_ui_font(int(9 * scale))
    
        # 1. Dynamic text wrapping
        words = icon_info['name'].split()
        lines = []
        current_line = ""
        hyphen = "-"

        def split_long_word(word):
            if font.getlength(word) <= s_max_line:
                return [word]

            parts = []
            rest = word
            while rest:
                if font.getlength(rest) <= s_max_line:
                    parts.append(rest)
                    break

                chunk = ""
                for char in rest:
                    candidate = chunk + char
                    candidate_with_hyphen = candidate + hyphen
                    if font.getlength(candidate_with_hyphen) <= s_max_line:
                        chunk = candidate
                    else:
                        break

                if not chunk:
                    chunk = rest[0]

                consumed = len(chunk)
                if consumed < len(rest):
                    parts.append(chunk + hyphen)
                    rest = rest[consumed:]
                else:
                    parts.append(chunk)
                    break

            return parts

        for word in words:
            chunks = split_long_word(word)
            for idx, chunk in enumerate(chunks):
                needs_space = (idx == 0)
                spacer = " " if (current_line and needs_space) else ""
                test_line = current_line + spacer + chunk

                if font.getlength(test_line) <= s_max_line:
                    current_line = test_line
                else:
                    if current_line:
                        lines.append(current_line)
                    current_line = chunk
        lines.append(current_line)
        
        line_height = int(12 * scale)
        actual_text_height = max(s_text_h_min, (len(lines) * line_height) + int(10 * scale))
        
        tooltip_comment = icon_info.get('comment') if show_tooltip else None

        # Total dimensions: event area + text field
        canvas_h = s_event + actual_text_height
        canvas = Image.new("RGBA", (canvas_w, canvas_h), (0, 0, 0, 0))
        draw = ImageDraw.Draw(canvas)
        is_selected = (icon_index == self.last_click_index)
    
        # 2. Icon with cache logic (SVG/PNG)
        if icon_info['icon_path']:
            cache_key = (icon_info['icon_path'], s_icon, is_hover and not is_selected)
            if cache_key in self.icon_cache:
                img = self.icon_cache[cache_key]
            else:
                try:
                   # Pillow loads SVGs; for perfect scaling, librsvg is used in the background
                   if icon_info['icon_path'].endswith('.svg'):
                       # Convert SVG to PNG (in-memory)
                       png_data = svg2png(url=icon_info['icon_path'], parent_width=s_icon, parent_height=s_icon)
                       img = Image.open(io.BytesIO(png_data))
                   else:
                       img = Image.open(icon_info['icon_path'])
                   
                   img = img.convert("RGBA").resize((s_icon, s_icon), Image.Resampling.LANCZOS)

                   if is_hover and not is_selected:
                       img = ImageEnhance.Brightness(img).enhance(1.3)
                   self.icon_cache[cache_key] = img

                except Exception as e:
                    print(f"Fehler bei Icon {icon_info['icon_path']}: {e}")
                    img = None
    
            if img:
                icon_x = (canvas_w - s_icon) // 2
                # Centered in the event area (1px top/bottom padding for +2px)
                canvas.paste(img, (icon_x, int(1 * scale)), img)
    
        # 3. Cinnamon text field logic
        text_bg_y = s_event
        if is_selected:
            t_bg, t_fill = self.selection_bg, self.text_selected
        elif is_hover:
            t_bg, t_fill = self.hover_bg, self.text_hover
        else:
            t_bg, t_fill = self.label_bg, self.text_normal
    
        # Draw background (hover/selected)
        if t_bg[3] > 0:
            draw.rectangle([0, text_bg_y, s_text_w, text_bg_y + actual_text_height], fill=t_bg)
        elif t_fill == (255, 255, 255, 255):
            # Text shadow (drop shadow) for transparency mode
            sh_off = int(1 * scale)
            sh_col = (0, 0, 0, 180)
            curr_y = text_bg_y + int(5 * scale)
            for line in lines:
                tx = (canvas_w - font.getlength(line)) // 2
                draw.text((tx+sh_off, curr_y+sh_off), line, fill=sh_col, font=font)
                curr_y += line_height
    
        # Draw actual text
        curr_y = text_bg_y + int(5 * scale)
        for line in lines:
            tx = (canvas_w - font.getlength(line)) // 2
            draw.text((tx, curr_y), line, fill=t_fill, font=font)
            curr_y += line_height
    
        # 4. Tooltip (comment from .desktop)
        tooltip_canvas = None
        tooltip_pos = None
        if tooltip_comment:
            tw = int(tooltip_font.getlength(tooltip_comment) + int(10 * scale))
            th = int(16 * scale)
            tooltip_canvas = Image.new("RGBA", (tw, th), (255, 255, 220, 255))
            tooltip_draw = ImageDraw.Draw(tooltip_canvas)
            tooltip_draw.rectangle([0, 0, tw - 1, th - 1], outline=(0, 0, 0, 255))
            tooltip_draw.text((int(5 * scale), int(2 * scale)), tooltip_comment, fill=(0, 0, 0, 255), font=tooltip_font)

            icon_x = (canvas_w - s_icon) // 2
            start_x = int(icon_info['x'] * scale)
            start_y = int(icon_info['y'] * scale)
            abs_icon_x = start_x + icon_x
            abs_icon_y = start_y + int(1 * scale)

            # Left-aligned to the left edge of the icon region, slightly offset upward
            region_left = int(icon_info['icon_rect'][0] * scale)
            tip_x = region_left
            tip_y = abs_icon_y - th - int(6 * scale)
            max_w = self.width * scale
            max_h = self.height * scale
            tip_x = max(0, min(tip_x, max_w - tw))
            tip_y = max(0, min(tip_y, max_h - th))
            tooltip_pos = (tip_x, tip_y)
    
        # 5. Wayland mmap transfer
        raw_data = canvas.tobytes("raw", "BGRA")
        start_x, start_y = int(icon_info['x'] * scale), int(icon_info['y'] * scale)
        for row in range(canvas_h):
            if start_y + row >= (self.height * scale): break
            target_pos = ((start_y + row) * buffer_pixel_width + start_x) * 4
            mm[target_pos : target_pos + (canvas_w * 4)] = raw_data[row*canvas_w*4 : (row+1)*canvas_w*4]

        # Blit tooltip as a separate overlay (without affecting icon canvas)
        if tooltip_canvas and tooltip_pos:
            tip_x, tip_y = tooltip_pos
            tip_w, tip_h = tooltip_canvas.size
            tip_raw = tooltip_canvas.tobytes("raw", "BGRA")
            max_w = self.width * scale
            max_h = self.height * scale

            for row in range(tip_h):
                target_y = tip_y + row
                if target_y < 0 or target_y >= max_h:
                    continue

                src_x = 0
                target_x = tip_x
                copy_w = tip_w

                if target_x < 0:
                    src_x = -target_x
                    copy_w -= src_x
                    target_x = 0

                if target_x + copy_w > max_w:
                    copy_w = max_w - target_x

                if copy_w <= 0:
                    continue

                src_pos = (row * tip_w + src_x) * 4
                dst_pos = ((target_y * buffer_pixel_width) + target_x) * 4
                mm[dst_pos : dst_pos + (copy_w * 4)] = tip_raw[src_pos : src_pos + (copy_w * 4)]

    def draw_context_menu(self, mm, buffer_pixel_width, scale):
        """
        Renders the context menu into the current mmap buffer.
        
        Parameters
        ----------
        mm : mmap.mmap
            Mmap buffer of the current frame.
        
        buffer_pixel_width : int
            Width of the target buffer in pixels.
        
        scale : int
            Current output scaling factor.
        """
        if not self.menu_visible:
            return

        s_w = max(1, int(self.menu_width * scale))
        s_item_h = max(1, int(self.menu_item_height * scale))
        s_h = s_item_h * len(self.menu_items)

        menu_canvas = Image.new("RGBA", (s_w, s_h), (26, 26, 26, 235))
        draw = ImageDraw.Draw(menu_canvas)
        draw.rectangle([0, 0, s_w - 1, s_h - 1], outline=(90, 90, 90, 255))

        font = self.get_ui_font(max(9, int(10 * scale)))

        for i, item in enumerate(self.menu_items):
            y = i * s_item_h
            if i > 0:
                draw.line([(0, y), (s_w - 1, y)], fill=(70, 70, 70, 255), width=1)
            draw.text((int(8 * scale), y + int(7 * scale)), item, fill=(255, 255, 255, 255), font=font)

        raw_data = menu_canvas.tobytes("raw", "BGRA")
        start_x = int(self.menu_pos[0] * scale)
        start_y = int(self.menu_pos[1] * scale)
        max_w = self.width * scale
        max_h = self.height * scale

        for row in range(s_h):
            target_y = start_y + row
            if target_y < 0 or target_y >= max_h:
                continue

            src_x = 0
            target_x = start_x
            copy_w = s_w

            if target_x < 0:
                src_x = -target_x
                copy_w -= src_x
                target_x = 0

            if target_x + copy_w > max_w:
                copy_w = max_w - target_x

            if copy_w <= 0:
                continue

            src_pos = (row * s_w + src_x) * 4
            target_pos = ((target_y * buffer_pixel_width) + target_x) * 4
            mm[target_pos : target_pos + (copy_w * 4)] = raw_data[src_pos : src_pos + (copy_w * 4)]

    def refresh_desktop(self):
        """
        Re-renders the desktop and commits the new buffer.
        """
        # Abort if surface has not yet been confirmed by the server
        if not self.surface or not self.configured or self.width == 0:
            return
        
        pixel_width, pixel_height = self.width * self.scale, self.height * self.scale
        buffer, mm = self.create_buffer(pixel_width, pixel_height)
        # Re-enable debug background (gray) if needed:
        # mm[:] = b'\x80\x80\x80\x80' * (pixel_width * pixel_height)
        mm[:] = b'\x00\x00\x00\x00' * (pixel_width * pixel_height)

        for i, icon in enumerate(self.icons):
            self.draw_icon_with_label(mm, pixel_width, icon, (i == self.hover_index), (i == self.hover_index and self.tooltip_visible), self.scale, i)

        self.draw_context_menu(mm, pixel_width, self.scale)

        self.surface.attach(buffer, 0, 0)
        self.surface.damage(0, 0, self.width, self.height)
        self.update_input_regions() 
        self.surface.commit()

    # --- Pointer / Interaction ---
    def setup_pointer(self):
        """
        Initializes pointer object and registers event handlers.
        """
        if not self.seat or self.pointer is not None:
            return
        
        self.pointer = self.seat.get_pointer()
        if self.input_debug:
            print("🖱️ Pointer initialisiert.")
        self.pointer.dispatcher['enter'] = self._on_pointer_enter
        self.pointer.dispatcher['leave'] = self._on_pointer_leave
        self.pointer.dispatcher['motion'] = self._on_pointer_motion
        self.pointer.dispatcher['button'] = self._on_pointer_button

    def _on_pointer_enter(self, pointer, serial, surface, sx, sy):
        """
        Sets start position and hover state when entering the surface.
        
        Parameters
        ----------
        pointer : object
            Wayland pointer object.
        
        serial : int
            Event serial from the compositor.
        
        surface : object
            Affected Wayland surface.
        
        sx : float
            Pointer X position relative to the surface.
        
        sy : float
            Pointer Y position relative to the surface.
        """
        self.mouse_x, self.mouse_y = float(sx), float(sy)
        self.last_motion_time = time.time()
        if self.input_debug:
            print(f"🖱️ enter @ {self.mouse_x:.1f},{self.mouse_y:.1f}")

    def _on_pointer_leave(self, pointer, serial, surface):
        """
        Resets hover/tooltip when the pointer leaves the surface.
        
        Parameters
        ----------
        pointer : object
            Wayland pointer object.
        
        serial : int
            Event serial from the compositor.
        
        surface : object
            Left Wayland surface.
        """
        if self.hover_index != -1 or self.tooltip_visible:
            self.hover_index = -1
            self.tooltip_visible = False
            self.refresh_desktop()
        if self.input_debug:
            print("🖱️ leave")

    def _on_pointer_motion(self, pointer, time_ms, sx, sy):
        """
        Processes pointer movements and updates hover state.
        
        Parameters
        ----------
        pointer : object
            Wayland pointer object.
        
        time_ms : int
            Event timestamp in milliseconds.
        
        sx : float
            Pointer X position relative to the surface.
        
        sy : float
            Pointer Y position relative to the surface.
        """
        # Store current mouse position (sx/sy are floats from Wayland)
        self.mouse_x, self.mouse_y = float(sx), float(sy)
        if self.input_debug:
            print(f"🖱️ motion @ {self.mouse_x:.1f},{self.mouse_y:.1f}")

        if self.left_pressed and self.pressed_icon_index != -1:
            delta_x = self.mouse_x - self.drag_start_mouse[0]
            delta_y = self.mouse_y - self.drag_start_mouse[1]

            if self.dragging_index == -1:
                if (abs(delta_x) >= self.drag_threshold) or (abs(delta_y) >= self.drag_threshold):
                    self.dragging_index = self.pressed_icon_index

            if self.dragging_index != -1:
                icon = self.icons[self.dragging_index]
                new_x = int(self.drag_start_icon[0] + delta_x)
                new_y = int(self.drag_start_icon[1] + delta_y)
                max_x = max(0, self.width - self.icon_size)
                max_y = max(0, self.height - self.icon_size)
                new_x = max(0, min(new_x, max_x))
                new_y = max(0, min(new_y, max_y))

                if new_x != int(icon['x']) or new_y != int(icon['y']):
                    icon['x'] = new_x
                    icon['y'] = new_y
                    self._update_icon_hitboxes(icon)
                    self.hover_index = self.dragging_index
                    self.tooltip_visible = False
                    self.refresh_desktop()
                return

        old_hover = self.hover_index
        new_hover = -1

        # Check against the rects calculated in load_desktop_entries
        for i, icon in enumerate(self.icons):
            # Icon Hitbox check
            ix, iy, iw, ih = icon['icon_rect']
            if ix <= self.mouse_x <= ix + iw and iy <= self.mouse_y <= iy + ih:
                new_hover = i
                break
            
            # Text Hitbox check
            tx, ty, tw, th = icon['text_rect']
            if tx <= self.mouse_x <= tx + tw and ty <= self.mouse_y <= ty + th:
                new_hover = i
                break

        if old_hover != new_hover:
            self.hover_index = new_hover
            self.tooltip_visible = False
            self.last_motion_time = time.time()
            print(f"🔍 Hover-Index: {self.hover_index}")
            self.refresh_desktop()

    def _on_pointer_button(self, pointer, serial, timestamp, button, state):
        """
        Handles pointer clicks for icons and context menu.
        
        Parameters
        ----------
        pointer : object
            Wayland pointer object.
        
        serial : int
            Event serial from the compositor.
        
        timestamp : int
            Event timestamp.
        
        button : int
            Button code (e.g. 272 left, 273 right).
        
        state : int
            Button state (1 pressed, 0 released).
        """
        if self.input_debug:
            print(f"🖱️ button={button} state={state} hover={self.hover_index}")
        left_buttons = {272, 0x110, 1}
        right_buttons = {273, 0x111, 3}
        middle_buttons = {274, 0x112, 2}

        if state == 1: # Button Pressed
            # If the menu is open, check menu click first
            if self.menu_visible:
                # Check whether click is outside menu -> close menu
                mx, my = self.mouse_x, self.mouse_y
                if not (self.menu_pos[0] <= mx <= self.menu_pos[0] + self.menu_width and
                        self.menu_pos[1] <= my <= self.menu_pos[1] + (len(self.menu_items) * self.menu_item_height)):
                    self.menu_visible = False
                    self.menu_icon_index = -1
                    self.update_input_regions()
                    self.refresh_desktop()
                    return
                else:
                    self.handle_menu_click(mx, my)
                    return

            # If user clicks on an icon
            if self.hover_index != -1:
                icon = self.icons[self.hover_index]
                
                if button in right_buttons: # Right click
                    self.menu_visible = True
                    self.menu_icon_index = self.hover_index
                    self.menu_pos = (self.mouse_x, self.mouse_y)
                    self.update_input_regions() 
                    self.refresh_desktop()

                elif button in middle_buttons: # Middle click (PCManFM integration)
                    print(f"📂 Öffne Ordner: {os.path.dirname(icon['path'])}")
                    subprocess.Popen(["pcmanfm", os.path.dirname(icon['path'])])

                elif button in left_buttons: # Left click
                    self.left_pressed = True
                    self.pressed_icon_index = self.hover_index
                    self.dragging_index = -1
                    self.drag_start_mouse = (self.mouse_x, self.mouse_y)
                    self.drag_start_icon = (float(icon['x']), float(icon['y']))
                    self.tooltip_visible = False

        elif state == 0 and button in left_buttons: # Button Released
            if self.left_pressed:
                was_dragging = self.dragging_index != -1
                clicked_index = self.pressed_icon_index
                self.left_pressed = False
                self.pressed_icon_index = -1
                self.dragging_index = -1

                if was_dragging:
                    if 0 <= clicked_index < len(self.icons):
                        self._snap_icon_to_grid(self.icons[clicked_index])
                        self.save_icon_positions()
                    self.update_input_regions()
                    self.refresh_desktop()
                elif clicked_index != -1 and clicked_index == self.hover_index:
                    now = time.time()
                    is_double_click = (
                        self.last_click_index == clicked_index and
                        (now - self.last_click_time) <= self.double_click_timeout
                    )

                    if is_double_click:
                        self.execute_icon(self.icons[clicked_index])
                        self.last_click_time = 0
                    else:
                        self.last_click_index = clicked_index
                        self.last_click_time = now
                        self.refresh_desktop()

    def handle_menu_click(self, mx, my):
        """
        Executes the selected context menu action for the active icon.
        
        Parameters
        ----------
        mx : float
            Mouse position X on click.
        
        my : float
            Mouse position Y on click.
        """
        # Calculate which menu index was clicked
        relative_y = my - self.menu_pos[1]
        item_index = int(relative_y // self.menu_item_height)
        
        if 0 <= item_index < len(self.menu_items):
            action = self.menu_items[item_index]
            if 0 <= self.menu_icon_index < len(self.icons):
                icon = self.icons[self.menu_icon_index]
            else:
                icon = self.icons[self.hover_index] if 0 <= self.hover_index < len(self.icons) else None
            if icon is None:
                self.menu_visible = False
                self.menu_icon_index = -1
                self.update_input_regions()
                self.refresh_desktop()
                return
            
            print(f"Menu-Aktion: {action} auf {icon['name']}")
            
            if action == "Öffnen":
                self.execute_icon(icon)
            elif action == "Mit PCManFM öffnen":
                subprocess.Popen(["pcmanfm", icon['path']])
            elif action == "Löschen":
                # Caution: Deletes the file from the desktop!
                if os.path.exists(icon['path']):
                    os.remove(icon['path'])
                    removed_key = self._icon_key(icon)
                    if removed_key in self.icon_positions:
                        del self.icon_positions[removed_key]
                        self.save_icon_positions()
            
        self.menu_visible = False
        self.menu_icon_index = -1
        self.update_input_regions()
        self.refresh_desktop()

    # --- Start / Runtime ---
    def execute_icon(self, icon):
        """
        Compatibility alias for icon launch via existing click paths.
        
        Parameters
        ----------
        icon : dict
            Icon record with launch information.
        """
        self.launch_icon(icon)

    def launch_icon(self, icon):
        """
        Launches a ".desktop" file or opens a path via "xdg-open".
        
        Parameters
        ----------
        icon : dict
            Icon record with at least "path" and optional "exec".
        """
        path = icon.get('path', '')
        if path.endswith('.desktop'):
            raw_cmd = icon.get('exec', '')
            cmd = raw_cmd.split('%')[0].strip()
        else:
            cmd = f"xdg-open '{path}'"
        
        if not cmd: return
        print(f"🚀 Starte: {cmd}")
        
        try:
            args = shlex.split(cmd)
            subprocess.Popen(args, start_new_session=True, 
                             stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except Exception as e:
            print(f"❌ Fehler: {e}")

    def run(self):
        """
        Starts the main loop for event processing and live reload.
        """
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        print("🚀 ldicons läuft. (Strg+C zum Beenden)")
        
        last_check = 0
        check_interval = 1.0  # Check files only once per second
        
        try:
            while True:
                # 1. Process events (mouse, resize, etc.)
                # According to pywayland, block=False does not read new events.
                # Therefore wait with select() on display FD and then dispatch in blocking mode.
                display_fd = self.display.get_fd()
                readable, _, _ = select.select([display_fd], [], [], 0.02)
                if readable:
                    self.display.dispatch(block=True)
                else:
                    self.display.dispatch(block=False)
                
                # 2. Time-critical tooltip logic (must run often)
                if self.hover_index != -1 and not self.tooltip_visible:
                    if time.time() - self.last_motion_time > self.tooltip_delay:
                        self.tooltip_visible = True
                        print("💡 Tooltip einblenden")
                        self.refresh_desktop()

                # 3. Expensive file checks (only every 1000ms)
                now = time.time()
                if now - last_check > check_interval:
                    self.check_config_reload()
                    self.check_desktop_reload()
                    last_check = now
                
                # 4. Send data to the server
                self.display.flush()
                
                # No additional sleep needed, select() paces the loop.
                
        except KeyboardInterrupt:
            print("\n👋 Beendet.")
        finally:
            if self.display:
                self.display.disconnect()

if __name__ == "__main__":
    cli_args = parse_cli_args()

    log_handle = setup_log_tee(cli_args.log)
    if log_handle is not None:
        atexit.register(log_handle.close)

    if cli_args.verbose:
        os.environ["ldicons_INPUT_DEBUG"] = "1"
        os.environ["PYDICONS_INPUT_DEBUG"] = "1"
        os.environ["DICONS_INPUT_DEBUG"] = "1"

    app = LDIcons(
        config_path=cli_args.conf,
        positions_path=cli_args.pos,
        verbose=cli_args.verbose,
    )

    # Force registry data retrieval (important for interfaces)
    print("🛰️ Synchronisiere Registry...")
    app.display.roundtrip() 

    # Surface Setup
    app.setup_desktop_surface()
    
    print("⏳ Warte auf Wayland-Konfiguration...")
    try:
        # dispatch(block=True) with short timeout or block=False
        print("Knock on... (dispatch(block=False))"),
        app.display.dispatch(block=False)
        print("Done.")

        # Send data to the Wayland server
        print("Flushing Events... "),
        app.display.flush()
        print("Done.")

        # IMPORTANT: Make a roundtrip that WAITS for the 'configure' event
        # This replaces your error-prone while loop
        print("⏳ Warte auf Server-Konfiguration (Layer Shell)...")
        app.display.roundtrip() 

    except Exception as e:
        # Sometimes read_events raises an error when the buffer is empty
        print(f"Wayland Dispatch Fehler: {e}")
        pass

    time.sleep(0.05)
    
    if app.configured:
        print(f"✅ Bereit! Größe: {app.width}x{app.height}")
        app.run()
    else:
        # If it still does not work, check whether everything was bound at all
        print("❌ Server hat die Surface nicht konfiguriert. Prüfe Schnittstellen...")
        print(f"Layer Shell: {app.layer_shell}, Compositor: {app.compositor}")
        print("Stelle sicher, dass dein Wayland-Compositor die zwlr_layer_shell_v1 \
            unterstützt und dass keine Fehler beim Binden der Schnittstellen \
                aufgetreten sind.")
        
        sys.exit(1)
    sys.exit(0)
    